### ISSUE TITLE
type error: a number is required

### ISSUE THREAD

**Issue by abdulazizalmass** [davidcdupuis/nfcattendancelogger#1]
Thank you very much. I like your code. It looks readable to me. 
Database and tables were created with no values. 
NFC Reader ACR122u seem to work because I was asked to enter name and surname, is that right?

Code issues:
1- ## _a number is required
.:. meaning I should write an id on the tag before scanning, right? what did you use to do that?
if you used gototags then what way?

2- It seems that the uid is redundant. How would you go about fixing that?
### error code

`UID is:
04 EA EF 7A
NFC.py:20: Warning: Truncated incorrect DOUBLE value: '04 EA EF 7A'  curs.execute(sql)
Traceback (most recent call last):
 File "NFC.py", line 63, in <module>
  Print "\n\nYour info: id = %d, uid = %s, name = %s, surname = %s" % (userUID,userName, userSurname)
TypeError: %d format: a number is required, not NonType`

One more thing. Thank you for the PDF

**Comment by abdulazizalmass** [comment]
once I had updated the AttendanceDB with an id to an existing added user, it said 
"there are no classes at this time today!" and the warning for redundancy is still on.

I a bit confused about the attendance system. Is this how you normal add new users? 
is it manually through the database or is it automatically from student' id card (nfc tag). 
if it was automatically,  how did you write the id on the tag before it was scanned ?
what sort of program or methodologies did you use in order to achieve that David?

**Comment by davidcdupuis** [comment]
Hey @abdulazizalmass, thanks for taking interest in my work. 

I'm a bit rusty on this project so I apologise if I'm not 100% clear.

Clearly there is an error in error code because there is a missing value in `% (userUID,userName, userSurname)` it should be `% (userId, userUID,userName, userSurname)` where `userId = result[0]`.

`if result is None` is the conditional if the user doesn't already exists and you want to add a user to the database, if it works it should print out all the users in the DB but then their should be an error because result is None and the rest of the code will still execute. (My mistake.) So you should assign the correct values of result in this conditional so that the rest of the code is executed correctly.

(If you are comfortable with Python I suggest you rewrite this code more properly otherwise I can help you with that.)

When the card is scanned the python code should be able to automatically find the uid with:
`uid = re.search(r'((\w){2}\s\s){4}',output).group(0).strip().split("  ")
uid = ' '.join(uid).upper()`

As you can see it does this correctly for you: "UID is: 04 EA EF 7A"

If you are not familiar with the code for the uid that I used, look into "regex" on google. 

Hope this helps ;)

**Comment by abdulazizalmass** [comment]
Thank you @davidcdupuis  for your replay. I feel comfortable using python and your help would be greatly appreciated^_^. 

---

you mentioned:

> Clearly there is an error in error code because there is a missing value in % (userUID,userName, userSurname) it should be % (userId, userUID,userName, userSurname) where userId = result[0]. 
> **so do I have to add the userId manually in AttendanceDB before I scan the tag? or what should I do?**

## progress update After adding a userId 11 to USER table

```
pi@raspberrypi:~/Downloads/nfcattendancelogger-master $ sudo python NFCRootDB.py 

UID is: 
04 EA EF 7A
NFCRootDB.py:20: Warning: Truncated incorrect DOUBLE value: '04 EA EF 7A'
  curs.execute(sql)

Your info: id = 11, uid = 4, name = aziz, surname = almas
CURRENT DATE: 
2016-03-07
CURRENT TIME: 
21:57:42.547986

There are no classes at this time today!
```

**The warning is still showing, do you know to stop this warning ?**
`Warning: Truncated incorrect DOUBLE value: '04 EA EF 7A'`

**Comment by abdulazizalmass** [comment]
This is the database bit I tried doing today, thank you @davidcdupuis  for your feedback.

I am not sure how you created TIMETABLE and ATTENDANCE tables.
**are the following tables creations correct?**

```
CREATE TABLE TIMETABLE(
classId NUMERIC(10)     PRIMARY KEY,
userId NUMERIC(15)      UNIQUE,

CONSTRAINT TimetableClassId FOREIGN KEY (classId)
REFERENCES CLASS(id) ON DELETE CASCADE ON UPDATE CASCADE,   
CONSTRAINT imetableUserId FOREIGN KEY (userId)
REFERENCES USER(id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB;

CREATE TABLE ATTENDANCE(
classId NUMERIC(10)     PRIMARY KEY,
userId NUMERIC(15)      UNIQUE,

CONSTRAINT AttendanceClassId FOREIGN KEY (classId)
REFERENCES CLASS(id) ON DELETE CASCADE ON UPDATE CASCADE,   
CONSTRAINT AttendanceUserId FOREIGN KEY (userId)
REFERENCES USER(id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB;
```

**is this how you added class stime and etime?**

```
INSERT INTO CLASS (id, name, tdate, stime, etime)
VALUES (6087,'AI', STR_TO_DATE('08-03-2016','%d-%m-%Y'), 
ADDTIME('2016-03-08 02:00:00.000001', '2.000001'), 
ADDTIME('2016-03-08 03:00:00.000001', '2.000001'));

INSERT INTO CLASS 
VALUES (6102,'FINAL Proj', STR_TO_DATE('08-03-2016','%d-%m-%Y'), 
ADDTIME('2016-03-08 03:00:00.000001', '2.000001'), 
ADDTIME('2016-03-08 04:00:00.000001', '2.000001'));

INSERT INTO CLASS 
VALUES (6089,'Usability Eng', STR_TO_DATE('10-03-2016','%d-%m-%Y'), 
ADDTIME('2016-03-10 11:00:00.000001', '2.000001'), 
ADDTIME('2016-03-10 12:00:00.000001', '2.000001'));
```

**how do I add user into TIMETABLE?**
I tried this:
`mysql> INSERT INTO TIMETABLE (classId, userId) VALUES (6087, 11);`
`ERROR 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`AttendanceDB`.`TIMETABLE`, CONSTRAINT`imetableUserId`FOREIGN KEY (`userId`) REFERENCES`USER`(`id`) ON DELETE CASCADE ON UPDATE CASCADE)`
**I do not know how to fix this above error, please help**

...
If you need to read all of the sql database script, it is ready and available on your request. 

and... sorry for the long writing.

**Comment by davidcdupuis** [comment]
@abdulazizalmass make sure your sql commands are correct, I did not bother using Cascade when I made mine. I also can tell you that the uId cannot be numeric. It has to be a string since there are letters in it. I'll try to find the SQL commands I used to create the tables but with no guarantee. 

The script I use asks you to add the user if he doesn't exist in the database.

**Comment by abdulazizalmass** [comment]
don't worry. it has been sorted.
I just need your programming thinking if you could help...
case scenario:
let say you had 10 NFC readers, 
how would you know the exact reader if a user scanned their tag?
 how to uniquely identify NFC reader from other NFC readers?

I was thinking querying user's profile data. for example, if you scan, your name, Id and time of scan will be added in a table. but how to make an Identify the NFC reader in this scenario.

**Comment by abdulazizalmass** [comment]
Do you think it is possible to link an NFC Reader to an SQL table and the code will automatically identify this reader uniquely?

I asked stack overflow:
http://stackoverflow.com/questions/36138638/how-to-uniquely-identify-an-nfc-reader-from-other-nfc-readers

But I am not satisfied. You are an expert programmer.
Can you tell if it is possible?

**Comment by davidcdupuis** [comment]
You can identify the card id but I don't know if specific information is relayed by the reader. Possibly a product id? When I was first exploring the possibilities with the card reader I used a software that relayed information from the reader. I'm not sure of the name but you could probably find it at ww.acs.com.hk/en/utility-tools. You'll have to explore on your own and compare two different readers to see if you can find a product identification. Otherwise it seems like grundyoso may be right you'll have to buy new more modern NFC readers.

**Comment by abdulazizalmass** [comment]
Thank you very much for your constructive feedback. I really appreciate it.
The presentation was done. You can watch my presentation from my YouTube channel over [here](https://www.youtube.com/watch?v=dVkvlFFu8fY).
Now I will be working on the evaluation report. Then I will git my project on github.
